[project]
name = "reacher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "torch==2.4.0",
  "isaacsim==4.2.0.2",
  "isaacsim-extscache-physics==4.2.0.2",
  "isaacsim-extscache-kit==4.2.0.2",
  "isaacsim-extscache-kit-sdk==4.2.0.2",
  "isaacsim-rl>=4.2.0.2",
  "isaacsim-replicator>=4.2.0.2",
  "isaacsim-app>=4.2.0.2",
  "pip>=24.3.1",
  "gymnasium-robotics>=1.3.1",
  "minari>=0.5.2",
  "diffusers>=0.31.0",
  "pyqt5>=5.15.11",
  "opencv-python-headless>=4.10.0.84",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu118", marker = "platform_system != 'Darwin'" },
]


[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

