defaults:
  - model: unet
  - _self_

logger: wandb
wandb_project: locodiff_isaac
num_iters: 5e5
seed: 42
resume: false
episode_length: 5

# training
log_interval: 100
eval_interval: 1e3
sim_interval: 5e3
device: cuda
ema_decay: 0.999
use_ema: True

#dims
obs_dim: null
act_dim: null
T: 57
T_cond: 8
T_action: 20
num_envs: 64

# diffusion
sampling_steps: 10
cond_mask_prob: 0

policy:
  obs_dim: ${obs_dim}
  act_dim: ${act_dim}
  T: ${T}
  T_cond: ${T_cond}
  T_action: ${T_action}
  num_envs: ${num_envs}
  sampling_steps: ${sampling_steps}
  sampler_type: ddim_resample
  sigma_data: 0.5
  sigma_min: 0.005
  sigma_max: 1
  cond_lambda: 1
  cond_mask_prob: ${cond_mask_prob}
  lr: 1e-4
  betas: [0.9, 0.999]
  num_iters: ${num_iters}
  inpaint_obs: true
  inpaint_final_obs: true
  device: ${device}
  resampling_steps: 40
  jump_length: 1

dataset:
  data_directory: logs/rsl_rl/cartpole_collect/hdf_dataset.hdf5
  train_fraction: 0.95
  device: ${device}
  T_cond: ${T_cond}
  T: ${T}
  train_batch_size: 1024
  test_batch_size: 1024
  num_workers: 4
  scaling: linear
  task_name: null

hydra:
  run:
    dir: logs/diffusion/cartpole/${now:%b-%d}/${now:%H-%M-%S}
