num_learning_iterations: 1e6
num_envs: 32
episode_length: 12
seed: 42
device: cuda
resume: False
log_interval: 1e3
eval_interval: 1e4
sim_interval: 5e4
save_interval: 1e4
wandb_project: latent_planning

video_length: 200
video_interval: 2000

algorithm:
  input_dim: 12
  latent_dim: 24
  hidden_dims: [256, 256]
  learning_rate: 1e-4
  goal: 0.01
  geco_lr: 5e-3
  am_lr: 0.03

dataset:
  data_directory: logs/latent_planning_record/hdf_dataset.hdf5
  train_fraction: 0.98
  train_batch_size: 1024
  test_batch_size: 1024
  num_workers: 4

