num_learning_iterations: 2e6
num_envs: 32
episode_length: 12
seed: 42
device: cuda
resume: False
log_interval: 1e3
eval_interval: 1e4
sim_interval: 5e4
save_interval: 1e4
wandb_project: reacher

video_length: 200
video_interval: 2000

policy:
  input_dim: 85
  latent_dim: 32
  hidden_dims: [2048, 2048, 2048, 2047]
  learning_rate: 1e-4
  goal: 1e-3
  geco_lr: 5e-3
  am_lr: 0.03
  prior_goal: 1.5
  num_envs: ${num_envs}

dataset:
  data_directory: logs/reacher_rl_record/hdf_dataset.hdf5
  train_fraction: 0.98
  train_batch_size: 1024
  test_batch_size: 1024
  num_workers: 4

hydra:
  run:
    dir: logs/reacher/${now:%b-%d}/${now:%H-%M-%S}
